/*
 * workflow_execution.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Ga4ghWesLog;
import io.swagger.client.model.Ga4ghWesParameter;
import io.swagger.client.model.Ga4ghWesState;
import io.swagger.client.model.Ga4ghWesWorkflowRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Ga4ghWesWorkflowLog
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-07T15:00:20.150-08:00")
public class Ga4ghWesWorkflowLog {
  @SerializedName("workflow_id")
  private String workflowId = null;

  @SerializedName("request")
  private Ga4ghWesWorkflowRequest request = null;

  @SerializedName("state")
  private Ga4ghWesState state = null;

  @SerializedName("workflow_log")
  private Ga4ghWesLog workflowLog = null;

  @SerializedName("task_logs")
  private List<Ga4ghWesLog> taskLogs = null;

  @SerializedName("outputs")
  private List<Ga4ghWesParameter> outputs = null;

  public Ga4ghWesWorkflowLog workflowId(String workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Get workflowId
   * @return workflowId
  **/
  @ApiModelProperty(value = "")
  public String getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(String workflowId) {
    this.workflowId = workflowId;
  }

  public Ga4ghWesWorkflowLog request(Ga4ghWesWorkflowRequest request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @ApiModelProperty(value = "")
  public Ga4ghWesWorkflowRequest getRequest() {
    return request;
  }

  public void setRequest(Ga4ghWesWorkflowRequest request) {
    this.request = request;
  }

  public Ga4ghWesWorkflowLog state(Ga4ghWesState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public Ga4ghWesState getState() {
    return state;
  }

  public void setState(Ga4ghWesState state) {
    this.state = state;
  }

  public Ga4ghWesWorkflowLog workflowLog(Ga4ghWesLog workflowLog) {
    this.workflowLog = workflowLog;
    return this;
  }

   /**
   * Get workflowLog
   * @return workflowLog
  **/
  @ApiModelProperty(value = "")
  public Ga4ghWesLog getWorkflowLog() {
    return workflowLog;
  }

  public void setWorkflowLog(Ga4ghWesLog workflowLog) {
    this.workflowLog = workflowLog;
  }

  public Ga4ghWesWorkflowLog taskLogs(List<Ga4ghWesLog> taskLogs) {
    this.taskLogs = taskLogs;
    return this;
  }

  public Ga4ghWesWorkflowLog addTaskLogsItem(Ga4ghWesLog taskLogsItem) {
    if (this.taskLogs == null) {
      this.taskLogs = new ArrayList<Ga4ghWesLog>();
    }
    this.taskLogs.add(taskLogsItem);
    return this;
  }

   /**
   * Get taskLogs
   * @return taskLogs
  **/
  @ApiModelProperty(value = "")
  public List<Ga4ghWesLog> getTaskLogs() {
    return taskLogs;
  }

  public void setTaskLogs(List<Ga4ghWesLog> taskLogs) {
    this.taskLogs = taskLogs;
  }

  public Ga4ghWesWorkflowLog outputs(List<Ga4ghWesParameter> outputs) {
    this.outputs = outputs;
    return this;
  }

  public Ga4ghWesWorkflowLog addOutputsItem(Ga4ghWesParameter outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<Ga4ghWesParameter>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @ApiModelProperty(value = "")
  public List<Ga4ghWesParameter> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<Ga4ghWesParameter> outputs) {
    this.outputs = outputs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ga4ghWesWorkflowLog ga4ghWesWorkflowLog = (Ga4ghWesWorkflowLog) o;
    return Objects.equals(this.workflowId, ga4ghWesWorkflowLog.workflowId) &&
        Objects.equals(this.request, ga4ghWesWorkflowLog.request) &&
        Objects.equals(this.state, ga4ghWesWorkflowLog.state) &&
        Objects.equals(this.workflowLog, ga4ghWesWorkflowLog.workflowLog) &&
        Objects.equals(this.taskLogs, ga4ghWesWorkflowLog.taskLogs) &&
        Objects.equals(this.outputs, ga4ghWesWorkflowLog.outputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflowId, request, state, workflowLog, taskLogs, outputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ga4ghWesWorkflowLog {\n");
    
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    workflowLog: ").append(toIndentedString(workflowLog)).append("\n");
    sb.append("    taskLogs: ").append(toIndentedString(taskLogs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

