/*
 * workflow_execution.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Ga4ghWesWorkflowDesc;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Ga4ghWesWorkflowListResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-07T15:00:20.150-08:00")
public class Ga4ghWesWorkflowListResponse {
  @SerializedName("workflows")
  private List<Ga4ghWesWorkflowDesc> workflows = null;

  @SerializedName("next_page_token")
  private String nextPageToken = null;

  public Ga4ghWesWorkflowListResponse workflows(List<Ga4ghWesWorkflowDesc> workflows) {
    this.workflows = workflows;
    return this;
  }

  public Ga4ghWesWorkflowListResponse addWorkflowsItem(Ga4ghWesWorkflowDesc workflowsItem) {
    if (this.workflows == null) {
      this.workflows = new ArrayList<Ga4ghWesWorkflowDesc>();
    }
    this.workflows.add(workflowsItem);
    return this;
  }

   /**
   * Get workflows
   * @return workflows
  **/
  @ApiModelProperty(value = "")
  public List<Ga4ghWesWorkflowDesc> getWorkflows() {
    return workflows;
  }

  public void setWorkflows(List<Ga4ghWesWorkflowDesc> workflows) {
    this.workflows = workflows;
  }

  public Ga4ghWesWorkflowListResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * Get nextPageToken
   * @return nextPageToken
  **/
  @ApiModelProperty(value = "")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ga4ghWesWorkflowListResponse ga4ghWesWorkflowListResponse = (Ga4ghWesWorkflowListResponse) o;
    return Objects.equals(this.workflows, ga4ghWesWorkflowListResponse.workflows) &&
        Objects.equals(this.nextPageToken, ga4ghWesWorkflowListResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflows, nextPageToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ga4ghWesWorkflowListResponse {\n");
    
    sb.append("    workflows: ").append(toIndentedString(workflows)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

