FROM ubuntu:16.04

# Update the APT cache
# prepare for Java download
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    python-software-properties \
    software-properties-common \
    tree \
    vim \
    postgresql-client \
    && apt-get clean

# grab oracle java (auto accept licence)
RUN add-apt-repository -y ppa:webupd8team/java \
    && apt-get update \
    && echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections \
    && apt-get install -y oracle-java8-installer

# install Consonance services
ENV consonance_version=2.0-alpha.9

RUN wget --no-verbose https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/consonance/consonance-arch/${consonance_version}/consonance-arch-${consonance_version}.jar 

RUN useradd -ms /bin/bash ubuntu 
# the web and Consonance config
WORKDIR /home/ubuntu

# install dockerize 
ENV DOCKERIZE_VERSION v0.2.0

RUN wget --no-verbose https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


# TODO: make sure you create these from the .template files and customize them
RUN mkdir -p /home/ubuntu/.youxia /home/ubuntu/.consonance /home/ubuntu/.consonance/self-installs /home/ubuntu/.ssh /home/ubuntu/bin
COPY config /home/ubuntu/.consonance/config
COPY key.pem /home/ubuntu/.ssh/key.pem
COPY initclient.sh /home/ubuntu/initclient.sh

RUN chmod 600 /home/ubuntu/.ssh/key.pem 
RUN chmod a+wrx /home/ubuntu/initclient.sh
RUN chown -R ubuntu /home/ubuntu
USER ubuntu
RUN echo "postgres:5432:*:*:postgres" > /home/ubuntu/.pgpass && chmod 600 /home/ubuntu/.pgpass


# for youxia and the consonance command line on the main box 
RUN wget --no-verbose https://github.com/Consonance/consonance/releases/download/${consonance_version}/consonance && mv consonance /home/ubuntu/bin && chmod a+x /home/ubuntu/bin/consonance
RUN wget --no-verbose --no-check-certificate http://wrench.res.oicr.on.ca/artifactory/seqware-release/io/consonance/consonance-client/${consonance_version}/consonance-client-${consonance_version}.jar && mv consonance-client-${consonance_version}.jar /home/ubuntu/.consonance/self-installs/

# now get a sample CWL and test JSON
RUN wget --no-verbose https://raw.githubusercontent.com/briandoconnor/dockstore-tool-bamstats/develop/Dockstore.cwl
RUN wget --no-verbose https://raw.githubusercontent.com/briandoconnor/dockstore-tool-bamstats/develop/sample_configs.json


ENV PATH="/home/ubuntu/bin:${PATH}"

CMD ["dockerize", "-wait", "tcp://webservice:8080", "-timeout", "10s", "/home/ubuntu/initclient.sh"]
