FROM ubuntu:16.04

# Update the APT cache
# prepare for Java download
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    python-software-properties \
    software-properties-common \
    telnet \
    && apt-get clean

# grab oracle java (auto accept licence)
RUN add-apt-repository -y ppa:webupd8team/java \
    && apt-get update \
    && echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections \
    && apt-get install -y oracle-java8-installer

# install Consonance services
ENV consonance_version=cgp-2.0.0-alpha.16

# Switch to BD2K fork over Consonance source for reaping fix
RUN wget --no-verbose https://github.com/BD2KGenomics/consonance/releases/download/${consonance_version}/consonance-webservice-${consonance_version}.jar
#RUN wget --no-verbose https://github.com/Consonance/consonance/releases/download/${consonance_version}/consonance-webservice-${consonance_version}.jar
#https://www.dropbox.com/s/3izdg4g6wv44xl4/consonance-webservice-2.0-alpha.11-SNAPSHOT.jar
#RUN wget --no-verbose https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/consonance/consonance-webservice/${consonance_version}/consonance-webservice-${consonance_version}.jar

# install dockerize
ENV DOCKERIZE_VERSION v0.2.0

RUN wget --no-verbose https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# the web and Consonance config
COPY config .
COPY web.yml .
ADD init_webservice.sh .

RUN chmod u+x init_webservice.sh
# TODO: make sure you create these from the .template files and customize them
COPY config /root/.consonance/config
RUN mkdir /consonance_logs && chmod a+rx /consonance_logs

# TODO: 1) update the above to have my AWS creds in it and 2) create the admin user in postgres db
# Waiting for postgres and rabbitmq services
CMD ["dockerize", "-wait", "tcp://postgres:5432", "-wait", "tcp://rabbitmq:5672", "-timeout", "60s", "./init_webservice.sh"]